/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Aditya Sonone
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdiv = new javax.swing.JTextField();
        txtRoll = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtUpdatename = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUpdatedRoll = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUpdateDiv = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtDelete = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDisplay = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Students Database Management");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel3.setText("Division");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 212, -1, 38));

        jLabel4.setText("Rollno");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 168, -1, 38));

        txtdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdivActionPerformed(evt);
            }
        });
        getContentPane().add(txtdiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 212, 164, 38));
        getContentPane().add(txtRoll, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 168, 164, 38));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, -1, -1));

        jLabel5.setText("UpdateName");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 80, 20));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 118, 164, 38));

        txtUpdatename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdatenameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUpdatename, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 298, 170, -1));

        jLabel6.setText("UpdateRollno");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));

        txtUpdatedRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdatedRollActionPerformed(evt);
            }
        });
        getContentPane().add(txtUpdatedRoll, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 170, -1));

        jLabel7.setText("UpdateDivision");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 381, -1, -1));
        getContentPane().add(txtUpdateDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 170, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));
        getContentPane().add(txtDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 160, -1));

        jLabel8.setText("Enter Name To Delete Record");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        txtDisplay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDisplay.setText("Display");
        txtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(txtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));

        jLabel9.setText("Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 129, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Delete Records");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));
        // NOI18N

        jLabel11.setText("Update Last Entry");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        jLabel1.setText("Add Student Record in the Database.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String name = txtName.getText();
        String rollno = txtRoll.getText();
        String Div = txtdiv.getText();

        try {
            String url = "jdbc:mysql://localhost:3306/LabAssignment6";
            String username = "root";
            String password = "12110266";
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, username, password);
            Statement st=connection.createStatement();
            st.executeUpdate("Insert Into students(Name,Rollno,Division) values('" + name + "','" + rollno + "','" + Div + "')");
            JOptionPane.showMessageDialog(null, "Entry Added Successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Database Not Connected");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            
        String name = txtName.getText();
        String UpdatedName=txtUpdatename.getText();
        String rollno = txtRoll.getText();
        String UpdateRoll=txtUpdatedRoll.getText();
        String UpdateDiv=txtUpdateDiv.getText();
        
      
        String Div = txtdiv.getText();

        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/LabAssignment6","root","12110266");
            Statement statement=con.createStatement();
            String sql="update students set name='"+UpdatedName+"' , Rollno='"+UpdateRoll+"' , Division='"+UpdateDiv+"' where Name='"+name+"'  ";
            statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Record Successfully Updated");
        }catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }
          

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtUpdatenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdatenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdatenameActionPerformed

    private void txtUpdatedRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdatedRollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdatedRollActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         
        String DeleteUser=txtDelete.getText();
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/LabAssignment6","root","12110266");
            Statement statement=con.createStatement();
            String sql2=" delete from students where name='"+DeleteUser+"'  ";
            statement.executeUpdate(sql2);
            JOptionPane.showMessageDialog(null,"Record Deleted Successfully");
        }catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
        }        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisplayActionPerformed
       
        try{
        
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/LabAssignment6","root","12110266");
        Statement statement=con.createStatement();
        String sql3=" select * from students ";
        ResultSet resultset=statement.executeQuery(sql3);
 
        while(resultset.next()){
           System.out.println(resultset.getString(1)+" "+resultset.getInt(2)+" "+resultset.getString(3));
        }
        
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
         
        
        
        
        
    }//GEN-LAST:event_txtDisplayActionPerformed

    private void txtdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDelete;
    private javax.swing.JButton txtDisplay;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRoll;
    private javax.swing.JTextField txtUpdateDiv;
    private javax.swing.JTextField txtUpdatedRoll;
    private javax.swing.JTextField txtUpdatename;
    private javax.swing.JTextField txtdiv;
    // End of variables declaration//GEN-END:variables
}
